/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle.demo2;

import com.google.gson.Gson;
import org.apache.commons.math4.core.jdkmath.JdkMath;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Gson gson = new Gson();
        System.out.println(gson.toJson("Hello Worlds!") );
        double pi = JdkMath.PI;
        System.out.println("pi: " + pi);
    }
}
